spring:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/tg_system?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
#      password: ENC(b23VDk+4wxd1D0EJ/F6JgQHYqg5iv7EjG+KMcVbajd8=)
      hikari:
        maximum-pool-size: 60
        connection-timeout: 50000
        idle-timeout: 30000
        max-lifetime: 1000000
        auto-commit: true
        pool-name: Hikari-Pool
        connection-test-query: select 1