spring:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tg_system?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      hikari:
        maximum-pool-size: 60
        connection-timeout: 50000
        idle-timeout: 30000
        max-lifetime: 1000000
        auto-commit: true
        pool-name: Hikari-Pool
        connection-test-query: select 1